services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./express-backend
    ports:
      - "3000:3000"
    depends_on:
      - liveness
    restart: unless-stopped

  liveness:
    build: ./sidecar
    ports:
      - "8000:8000"
    restart: unless-stopped
